// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD84sPARPC1lxwozZVjrmsbrGfmOXzt9t0',
    appId: '1:320217978026:web:6407eb25ef9bc398a3ecd3',
    messagingSenderId: '320217978026',
    projectId: 'pruebalsm-998c5',
    authDomain: 'pruebalsm-998c5.firebaseapp.com',
    databaseURL: 'https://pruebalsm-998c5-default-rtdb.firebaseio.com',
    storageBucket: 'pruebalsm-998c5.appspot.com',
    measurementId: 'G-01JKT266F1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6ZEt7Em4YzKBk68x2ErOuYu3g4AL9F5Q',
    appId: '1:320217978026:android:7478e45da213cbe6a3ecd3',
    messagingSenderId: '320217978026',
    projectId: 'pruebalsm-998c5',
    databaseURL: 'https://pruebalsm-998c5-default-rtdb.firebaseio.com',
    storageBucket: 'pruebalsm-998c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCODCtNq36K0ymz-l124YRF9GJWGtUBg7Q',
    appId: '1:320217978026:ios:1084a865014072d6a3ecd3',
    messagingSenderId: '320217978026',
    projectId: 'pruebalsm-998c5',
    databaseURL: 'https://pruebalsm-998c5-default-rtdb.firebaseio.com',
    storageBucket: 'pruebalsm-998c5.appspot.com',
    iosClientId: '320217978026-svf8rt8b7gk0lk65mkd75fu7dv7dgrj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.agenditabb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCODCtNq36K0ymz-l124YRF9GJWGtUBg7Q',
    appId: '1:320217978026:ios:f65022a8ed1fef17a3ecd3',
    messagingSenderId: '320217978026',
    projectId: 'pruebalsm-998c5',
    databaseURL: 'https://pruebalsm-998c5-default-rtdb.firebaseio.com',
    storageBucket: 'pruebalsm-998c5.appspot.com',
    iosClientId: '320217978026-fqo54l28qnv50qm5b6f1kucigfur88tc.apps.googleusercontent.com',
    iosBundleId: 'com.example.agenditabb.RunnerTests',
  );
}
